title: Static Blog
description: A modern static blog with Decap CMS
url: "https://setoviktor1-beep.github.io/decap-cms-blog" # CHANGE THIS

plugins:
  - jekyll-seo-tag

exclude:
  - admin
  - oauth-worker
  - node_modules
  - package.json
  - package-lock.json
